### ISSUE TITLE
Por.donde vas?

### ISSUE THREAD

**Issue by martasalvo** [ZeteESP/Busca-Facturas-FCRB-IDPS#1]
Solo falta que no se pierda entre tanta carpeta, que tal va la recursividad?

**Comment by ZeteESP** [comment]
Mañana lo pruebo, a ver si me pasa bien la carpeta de destino a FileCopy y lo coge bien la linea de comando! ;)

**Comment by ZeteESP** [comment]
Hola Marta!
Me da este error en la linea 225, pero no consigo ver que es exactamente. Supongo que es el "matches"... Lo comentamos...

![image](https://cloud.githubusercontent.com/assets/12733432/9911984/413ad4da-5ca5-11e5-935d-24c8744e0a32.png)
